spring: 
    profiles: 
        active: 
        - dev
        
---
spring: 
    profiles: dev
    application: 
        name: equip-lease-config-bonus-dev
        
---
spring: 
    profiles: test
    application: 
        name: equip-lease-config-bonus-test
        
#请保存为UTF-8格式